//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TNTWSSample.TNTWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TimeInTransitBinding", Namespace="http://www.ups.com/WSDL/XOLTWS/TNT/v1.0")]
    public partial class TimeInTransitService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private UPSSecurity uPSSecurityValueField;
        
        private System.Threading.SendOrPostCallback ProcessTimeInTransitOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TimeInTransitService() {
            this.Url = "https://wwwcie.ups.com/webservices/TimeInTransit";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public UPSSecurity UPSSecurityValue {
            get {
                return this.uPSSecurityValueField;
            }
            set {
                this.uPSSecurityValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ProcessTimeInTransitCompletedEventHandler ProcessTimeInTransitCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UPSSecurityValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onlinetools.ups.com/webservices/TimeInTransitBinding/v1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("TimeInTransitResponse", Namespace="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")]
        public TimeInTransitResponse ProcessTimeInTransit([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")] TimeInTransitRequest TimeInTransitRequest) {
            object[] results = this.Invoke("ProcessTimeInTransit", new object[] {
                        TimeInTransitRequest});
            return ((TimeInTransitResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessTimeInTransitAsync(TimeInTransitRequest TimeInTransitRequest) {
            this.ProcessTimeInTransitAsync(TimeInTransitRequest, null);
        }
        
        /// <remarks/>
        public void ProcessTimeInTransitAsync(TimeInTransitRequest TimeInTransitRequest, object userState) {
            if ((this.ProcessTimeInTransitOperationCompleted == null)) {
                this.ProcessTimeInTransitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessTimeInTransitOperationCompleted);
            }
            this.InvokeAsync("ProcessTimeInTransit", new object[] {
                        TimeInTransitRequest}, this.ProcessTimeInTransitOperationCompleted, userState);
        }
        
        private void OnProcessTimeInTransitOperationCompleted(object arg) {
            if ((this.ProcessTimeInTransitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessTimeInTransitCompleted(this, new ProcessTimeInTransitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", IsNullable=false)]
    public partial class UPSSecurity : System.Web.Services.Protocols.SoapHeader {
        
        private UPSSecurityUsernameToken usernameTokenField;
        
        private UPSSecurityServiceAccessToken serviceAccessTokenField;
        
        /// <remarks/>
        public UPSSecurityUsernameToken UsernameToken {
            get {
                return this.usernameTokenField;
            }
            set {
                this.usernameTokenField = value;
            }
        }
        
        /// <remarks/>
        public UPSSecurityServiceAccessToken ServiceAccessToken {
            get {
                return this.serviceAccessTokenField;
            }
            set {
                this.serviceAccessTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")]
    public partial class UPSSecurityUsernameToken {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")]
    public partial class ResponseShipListAddressType {
        
        private string townField;
        
        private string cityField;
        
        private string stateProvinceCodeField;
        
        private string countryCodeField;
        
        private string postcodePrimaryLowField;
        
        private string postcodePrimaryHighField;
        
        /// <remarks/>
        public string Town {
            get {
                return this.townField;
            }
            set {
                this.townField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string StateProvinceCode {
            get {
                return this.stateProvinceCodeField;
            }
            set {
                this.stateProvinceCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PostcodePrimaryLow {
            get {
                return this.postcodePrimaryLowField;
            }
            set {
                this.postcodePrimaryLowField = value;
            }
        }
        
        /// <remarks/>
        public string PostcodePrimaryHigh {
            get {
                return this.postcodePrimaryHighField;
            }
            set {
                this.postcodePrimaryHighField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")]
    public partial class CandidateType {
        
        private ResponseShipListAddressType addressField;
        
        /// <remarks/>
        public ResponseShipListAddressType Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")]
    public partial class CandidateResponseType {
        
        private CandidateType[] shipFromListField;
        
        private CandidateType[] shipToListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Candidate", IsNullable=false)]
        public CandidateType[] ShipFromList {
            get {
                return this.shipFromListField;
            }
            set {
                this.shipFromListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Candidate", IsNullable=false)]
        public CandidateType[] ShipToList {
            get {
                return this.shipToListField;
            }
            set {
                this.shipToListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")]
    public partial class EstimatedArrivalType {
        
        private PickupType arrivalField;
        
        private string businessDaysInTransitField;
        
        private PickupType pickupField;
        
        private string dayOfWeekField;
        
        private string customerCenterCutoffField;
        
        private string delayCountField;
        
        private string holidayCountField;
        
        private string restDaysField;
        
        private string totalTransitDaysField;
        
        /// <remarks/>
        public PickupType Arrival {
            get {
                return this.arrivalField;
            }
            set {
                this.arrivalField = value;
            }
        }
        
        /// <remarks/>
        public string BusinessDaysInTransit {
            get {
                return this.businessDaysInTransitField;
            }
            set {
                this.businessDaysInTransitField = value;
            }
        }
        
        /// <remarks/>
        public PickupType Pickup {
            get {
                return this.pickupField;
            }
            set {
                this.pickupField = value;
            }
        }
        
        /// <remarks/>
        public string DayOfWeek {
            get {
                return this.dayOfWeekField;
            }
            set {
                this.dayOfWeekField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerCenterCutoff {
            get {
                return this.customerCenterCutoffField;
            }
            set {
                this.customerCenterCutoffField = value;
            }
        }
        
        /// <remarks/>
        public string DelayCount {
            get {
                return this.delayCountField;
            }
            set {
                this.delayCountField = value;
            }
        }
        
        /// <remarks/>
        public string HolidayCount {
            get {
                return this.holidayCountField;
            }
            set {
                this.holidayCountField = value;
            }
        }
        
        /// <remarks/>
        public string RestDays {
            get {
                return this.restDaysField;
            }
            set {
                this.restDaysField = value;
            }
        }
        
        /// <remarks/>
        public string TotalTransitDays {
            get {
                return this.totalTransitDaysField;
            }
            set {
                this.totalTransitDaysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")]
    public partial class PickupType {
        
        private string dateField;
        
        private string timeField;
        
        /// <remarks/>
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")]
    public partial class ServiceSummaryType {
        
        private CodeDescriptionType serviceField;
        
        private string guaranteedIndicatorField;
        
        private string disclaimerField;
        
        private EstimatedArrivalType estimatedArrivalField;
        
        private string saturdayDeliveryField;
        
        private string saturdayDeliveryDisclaimerField;
        
        /// <remarks/>
        public CodeDescriptionType Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
        
        /// <remarks/>
        public string GuaranteedIndicator {
            get {
                return this.guaranteedIndicatorField;
            }
            set {
                this.guaranteedIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public string Disclaimer {
            get {
                return this.disclaimerField;
            }
            set {
                this.disclaimerField = value;
            }
        }
        
        /// <remarks/>
        public EstimatedArrivalType EstimatedArrival {
            get {
                return this.estimatedArrivalField;
            }
            set {
                this.estimatedArrivalField = value;
            }
        }
        
        /// <remarks/>
        public string SaturdayDelivery {
            get {
                return this.saturdayDeliveryField;
            }
            set {
                this.saturdayDeliveryField = value;
            }
        }
        
        /// <remarks/>
        public string SaturdayDeliveryDisclaimer {
            get {
                return this.saturdayDeliveryDisclaimerField;
            }
            set {
                this.saturdayDeliveryDisclaimerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")]
    public partial class CodeDescriptionType {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")]
    public partial class ResponseShipToType {
        
        private ResponseShipToAddressType addressField;
        
        /// <remarks/>
        public ResponseShipToAddressType Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")]
    public partial class ResponseShipToAddressType : ResponseShipFromAddressType {
        
        private string residentialAddressIndicatorField;
        
        /// <remarks/>
        public string ResidentialAddressIndicator {
            get {
                return this.residentialAddressIndicatorField;
            }
            set {
                this.residentialAddressIndicatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseShipToAddressType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")]
    public partial class ResponseShipFromAddressType {
        
        private string townField;
        
        private string cityField;
        
        private string stateProvinceCodeField;
        
        private string countryCodeField;
        
        private string countryField;
        
        private string postalCodeField;
        
        /// <remarks/>
        public string Town {
            get {
                return this.townField;
            }
            set {
                this.townField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string StateProvinceCode {
            get {
                return this.stateProvinceCodeField;
            }
            set {
                this.stateProvinceCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")]
    public partial class ResponseShipFromType {
        
        private ResponseShipFromAddressType addressField;
        
        /// <remarks/>
        public ResponseShipFromAddressType Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")]
    public partial class TransitResponseType {
        
        private ResponseShipFromType shipFromField;
        
        private ResponseShipToType shipToField;
        
        private string pickupDateField;
        
        private ShipmentWeightType shipmentWeightField;
        
        private InvoiceLineTotalType invoiceLineTotalField;
        
        private string documentsOnlyIndicatorField;
        
        private string billTypeField;
        
        private string maximumListSizeField;
        
        private ServiceSummaryType[] serviceSummaryField;
        
        private string autoDutyCodeField;
        
        private string disclaimerField;
        
        /// <remarks/>
        public ResponseShipFromType ShipFrom {
            get {
                return this.shipFromField;
            }
            set {
                this.shipFromField = value;
            }
        }
        
        /// <remarks/>
        public ResponseShipToType ShipTo {
            get {
                return this.shipToField;
            }
            set {
                this.shipToField = value;
            }
        }
        
        /// <remarks/>
        public string PickupDate {
            get {
                return this.pickupDateField;
            }
            set {
                this.pickupDateField = value;
            }
        }
        
        /// <remarks/>
        public ShipmentWeightType ShipmentWeight {
            get {
                return this.shipmentWeightField;
            }
            set {
                this.shipmentWeightField = value;
            }
        }
        
        /// <remarks/>
        public InvoiceLineTotalType InvoiceLineTotal {
            get {
                return this.invoiceLineTotalField;
            }
            set {
                this.invoiceLineTotalField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentsOnlyIndicator {
            get {
                return this.documentsOnlyIndicatorField;
            }
            set {
                this.documentsOnlyIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public string BillType {
            get {
                return this.billTypeField;
            }
            set {
                this.billTypeField = value;
            }
        }
        
        /// <remarks/>
        public string MaximumListSize {
            get {
                return this.maximumListSizeField;
            }
            set {
                this.maximumListSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ServiceSummary")]
        public ServiceSummaryType[] ServiceSummary {
            get {
                return this.serviceSummaryField;
            }
            set {
                this.serviceSummaryField = value;
            }
        }
        
        /// <remarks/>
        public string AutoDutyCode {
            get {
                return this.autoDutyCodeField;
            }
            set {
                this.autoDutyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Disclaimer {
            get {
                return this.disclaimerField;
            }
            set {
                this.disclaimerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")]
    public partial class ShipmentWeightType {
        
        private CodeDescriptionType unitOfMeasurementField;
        
        private string weightField;
        
        /// <remarks/>
        public CodeDescriptionType UnitOfMeasurement {
            get {
                return this.unitOfMeasurementField;
            }
            set {
                this.unitOfMeasurementField = value;
            }
        }
        
        /// <remarks/>
        public string Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")]
    public partial class InvoiceLineTotalType {
        
        private string currencyCodeField;
        
        private string monetaryValueField;
        
        /// <remarks/>
        public string CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MonetaryValue {
            get {
                return this.monetaryValueField;
            }
            set {
                this.monetaryValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class ElementIdentifierType {
        
        private string codeField;
        
        private string valueField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class ElementLevelInformationType {
        
        private string levelField;
        
        private ElementIdentifierType[] elementIdentifierField;
        
        /// <remarks/>
        public string Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ElementIdentifier")]
        public ElementIdentifierType[] ElementIdentifier {
            get {
                return this.elementIdentifierField;
            }
            set {
                this.elementIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class DetailType {
        
        private string codeField;
        
        private string descriptionField;
        
        private ElementLevelInformationType elementLevelInformationField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public ElementLevelInformationType ElementLevelInformation {
            get {
                return this.elementLevelInformationField;
            }
            set {
                this.elementLevelInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="CodeDescriptionType", Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class CodeDescriptionType1 {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class ResponseType {
        
        private CodeDescriptionType1 responseStatusField;
        
        private CodeDescriptionType1[] alertField;
        
        private DetailType[] alertDetailField;
        
        private TransactionReferenceType transactionReferenceField;
        
        /// <remarks/>
        public CodeDescriptionType1 ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Alert")]
        public CodeDescriptionType1[] Alert {
            get {
                return this.alertField;
            }
            set {
                this.alertField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AlertDetail")]
        public DetailType[] AlertDetail {
            get {
                return this.alertDetailField;
            }
            set {
                this.alertDetailField = value;
            }
        }
        
        /// <remarks/>
        public TransactionReferenceType TransactionReference {
            get {
                return this.transactionReferenceField;
            }
            set {
                this.transactionReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class TransactionReferenceType {
        
        private string customerContextField;
        
        private string transactionIdentifierField;
        
        /// <remarks/>
        public string CustomerContext {
            get {
                return this.customerContextField;
            }
            set {
                this.customerContextField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionIdentifier {
            get {
                return this.transactionIdentifierField;
            }
            set {
                this.transactionIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")]
    public partial class RequestShipToType {
        
        private RequestShipToAddressType addressField;
        
        /// <remarks/>
        public RequestShipToAddressType Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")]
    public partial class RequestShipToAddressType : RequestShipFromAddressType {
        
        private string residentialAddressIndicatorField;
        
        /// <remarks/>
        public string ResidentialAddressIndicator {
            get {
                return this.residentialAddressIndicatorField;
            }
            set {
                this.residentialAddressIndicatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestShipToAddressType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")]
    public partial class RequestShipFromAddressType {
        
        private string townField;
        
        private string cityField;
        
        private string stateProvinceCodeField;
        
        private string countryCodeField;
        
        private string postalCodeField;
        
        /// <remarks/>
        public string Town {
            get {
                return this.townField;
            }
            set {
                this.townField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string StateProvinceCode {
            get {
                return this.stateProvinceCodeField;
            }
            set {
                this.stateProvinceCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")]
    public partial class RequestShipFromType {
        
        private RequestShipFromAddressType addressField;
        
        /// <remarks/>
        public RequestShipFromAddressType Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class RequestType {
        
        private string[] requestOptionField;
        
        private TransactionReferenceType transactionReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RequestOption")]
        public string[] RequestOption {
            get {
                return this.requestOptionField;
            }
            set {
                this.requestOptionField = value;
            }
        }
        
        /// <remarks/>
        public TransactionReferenceType TransactionReference {
            get {
                return this.transactionReferenceField;
            }
            set {
                this.transactionReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")]
    public partial class UPSSecurityServiceAccessToken {
        
        private string accessLicenseNumberField;
        
        /// <remarks/>
        public string AccessLicenseNumber {
            get {
                return this.accessLicenseNumberField;
            }
            set {
                this.accessLicenseNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")]
    public partial class TimeInTransitRequest {
        
        private RequestType requestField;
        
        private RequestShipFromType shipFromField;
        
        private RequestShipToType shipToField;
        
        private PickupType pickupField;
        
        private ShipmentWeightType shipmentWeightField;
        
        private string totalPackagesInShipmentField;
        
        private InvoiceLineTotalType invoiceLineTotalField;
        
        private string documentsOnlyIndicatorField;
        
        private string billTypeField;
        
        private string maximumListSizeField;
        
        private string saturdayDeliveryInfoRequestIndicatorField;
        
        private string dropOffAtFacilityIndicatorField;
        
        private string holdForPickupIndicatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
        public RequestType Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        public RequestShipFromType ShipFrom {
            get {
                return this.shipFromField;
            }
            set {
                this.shipFromField = value;
            }
        }
        
        /// <remarks/>
        public RequestShipToType ShipTo {
            get {
                return this.shipToField;
            }
            set {
                this.shipToField = value;
            }
        }
        
        /// <remarks/>
        public PickupType Pickup {
            get {
                return this.pickupField;
            }
            set {
                this.pickupField = value;
            }
        }
        
        /// <remarks/>
        public ShipmentWeightType ShipmentWeight {
            get {
                return this.shipmentWeightField;
            }
            set {
                this.shipmentWeightField = value;
            }
        }
        
        /// <remarks/>
        public string TotalPackagesInShipment {
            get {
                return this.totalPackagesInShipmentField;
            }
            set {
                this.totalPackagesInShipmentField = value;
            }
        }
        
        /// <remarks/>
        public InvoiceLineTotalType InvoiceLineTotal {
            get {
                return this.invoiceLineTotalField;
            }
            set {
                this.invoiceLineTotalField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentsOnlyIndicator {
            get {
                return this.documentsOnlyIndicatorField;
            }
            set {
                this.documentsOnlyIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public string BillType {
            get {
                return this.billTypeField;
            }
            set {
                this.billTypeField = value;
            }
        }
        
        /// <remarks/>
        public string MaximumListSize {
            get {
                return this.maximumListSizeField;
            }
            set {
                this.maximumListSizeField = value;
            }
        }
        
        /// <remarks/>
        public string SaturdayDeliveryInfoRequestIndicator {
            get {
                return this.saturdayDeliveryInfoRequestIndicatorField;
            }
            set {
                this.saturdayDeliveryInfoRequestIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public string DropOffAtFacilityIndicator {
            get {
                return this.dropOffAtFacilityIndicatorField;
            }
            set {
                this.dropOffAtFacilityIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public string HoldForPickupIndicator {
            get {
                return this.holdForPickupIndicatorField;
            }
            set {
                this.holdForPickupIndicatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")]
    public partial class TimeInTransitResponse {
        
        private ResponseType responseField;
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
        public ResponseType Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CandidateResponse", typeof(CandidateResponseType))]
        [System.Xml.Serialization.XmlElementAttribute("TransitResponse", typeof(TransitResponseType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ProcessTimeInTransitCompletedEventHandler(object sender, ProcessTimeInTransitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessTimeInTransitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessTimeInTransitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TimeInTransitResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TimeInTransitResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591