//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DangerousGoodsWSSample.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DangerousGoodsUtilityBinding", Namespace="http://www.ups.com/WSDL/XOLTWS/DangerousGoodsUtility/v1.0")]
    public partial class DangerousGoodsUtility : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private UPSSecurity uPSSecurityValueField;
        
        private System.Threading.SendOrPostCallback ProcessAcceptanceAuditPreCheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessChemicalReferenceDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DangerousGoodsUtility() {
            this.Url = global::DangerousGoodsWSSample.Properties.Settings.Default.DangerousGoodsWSSample_WebReference_DangerousGoodsUtility;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public UPSSecurity UPSSecurityValue {
            get {
                return this.uPSSecurityValueField;
            }
            set {
                this.uPSSecurityValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ProcessAcceptanceAuditPreCheckCompletedEventHandler ProcessAcceptanceAuditPreCheckCompleted;
        
        /// <remarks/>
        public event ProcessChemicalReferenceDataCompletedEventHandler ProcessChemicalReferenceDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UPSSecurityValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onlinetools.ups.com/webservices/DangerousGoodsUtilityBinding/v1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("AcceptanceAuditPreCheckResponse", Namespace="http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0")]
        public AcceptanceAuditPreCheckResponse ProcessAcceptanceAuditPreCheck([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0")] AcceptanceAuditPreCheckRequest AcceptanceAuditPreCheckRequest) {
            object[] results = this.Invoke("ProcessAcceptanceAuditPreCheck", new object[] {
                        AcceptanceAuditPreCheckRequest});
            return ((AcceptanceAuditPreCheckResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessAcceptanceAuditPreCheckAsync(AcceptanceAuditPreCheckRequest AcceptanceAuditPreCheckRequest) {
            this.ProcessAcceptanceAuditPreCheckAsync(AcceptanceAuditPreCheckRequest, null);
        }
        
        /// <remarks/>
        public void ProcessAcceptanceAuditPreCheckAsync(AcceptanceAuditPreCheckRequest AcceptanceAuditPreCheckRequest, object userState) {
            if ((this.ProcessAcceptanceAuditPreCheckOperationCompleted == null)) {
                this.ProcessAcceptanceAuditPreCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessAcceptanceAuditPreCheckOperationCompleted);
            }
            this.InvokeAsync("ProcessAcceptanceAuditPreCheck", new object[] {
                        AcceptanceAuditPreCheckRequest}, this.ProcessAcceptanceAuditPreCheckOperationCompleted, userState);
        }
        
        private void OnProcessAcceptanceAuditPreCheckOperationCompleted(object arg) {
            if ((this.ProcessAcceptanceAuditPreCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessAcceptanceAuditPreCheckCompleted(this, new ProcessAcceptanceAuditPreCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UPSSecurityValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onlinetools.ups.com/webservices/DangerousGoodsUtilityBinding/v1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ChemicalReferenceDataResponse", Namespace="http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0")]
        public ChemicalReferenceDataResponse ProcessChemicalReferenceData([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0")] ChemicalReferenceDataRequest ChemicalReferenceDataRequest) {
            object[] results = this.Invoke("ProcessChemicalReferenceData", new object[] {
                        ChemicalReferenceDataRequest});
            return ((ChemicalReferenceDataResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessChemicalReferenceDataAsync(ChemicalReferenceDataRequest ChemicalReferenceDataRequest) {
            this.ProcessChemicalReferenceDataAsync(ChemicalReferenceDataRequest, null);
        }
        
        /// <remarks/>
        public void ProcessChemicalReferenceDataAsync(ChemicalReferenceDataRequest ChemicalReferenceDataRequest, object userState) {
            if ((this.ProcessChemicalReferenceDataOperationCompleted == null)) {
                this.ProcessChemicalReferenceDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessChemicalReferenceDataOperationCompleted);
            }
            this.InvokeAsync("ProcessChemicalReferenceData", new object[] {
                        ChemicalReferenceDataRequest}, this.ProcessChemicalReferenceDataOperationCompleted, userState);
        }
        
        private void OnProcessChemicalReferenceDataOperationCompleted(object arg) {
            if ((this.ProcessChemicalReferenceDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessChemicalReferenceDataCompleted(this, new ProcessChemicalReferenceDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", IsNullable=false)]
    public partial class UPSSecurity : System.Web.Services.Protocols.SoapHeader {
        
        private UPSSecurityUsernameToken usernameTokenField;
        
        private UPSSecurityServiceAccessToken serviceAccessTokenField;
        
        /// <remarks/>
        public UPSSecurityUsernameToken UsernameToken {
            get {
                return this.usernameTokenField;
            }
            set {
                this.usernameTokenField = value;
            }
        }
        
        /// <remarks/>
        public UPSSecurityServiceAccessToken ServiceAccessToken {
            get {
                return this.serviceAccessTokenField;
            }
            set {
                this.serviceAccessTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")]
    public partial class UPSSecurityUsernameToken {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0")]
    public partial class PackageQuantityLimitDetailType {
        
        private string packageQuantityLimitTypeCodeField;
        
        private string quantityField;
        
        private string uOMField;
        
        private string packagingInstructionCodeField;
        
        /// <remarks/>
        public string PackageQuantityLimitTypeCode {
            get {
                return this.packageQuantityLimitTypeCodeField;
            }
            set {
                this.packageQuantityLimitTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public string UOM {
            get {
                return this.uOMField;
            }
            set {
                this.uOMField = value;
            }
        }
        
        /// <remarks/>
        public string PackagingInstructionCode {
            get {
                return this.packagingInstructionCodeField;
            }
            set {
                this.packagingInstructionCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0")]
    public partial class ChemicalDetailType {
        
        private string regulationSetField;
        
        private string iDNumberField;
        
        private string hazardousMaterialsDescriptionField;
        
        private string classDivisionNumberField;
        
        private string subRiskClassField;
        
        private string packagingGroupTypeField;
        
        private string specialPermitField;
        
        private string technicalNameRequiredIndicatorField;
        
        private string additionalShippingInformationRequiredIndicatorField;
        
        /// <remarks/>
        public string RegulationSet {
            get {
                return this.regulationSetField;
            }
            set {
                this.regulationSetField = value;
            }
        }
        
        /// <remarks/>
        public string IDNumber {
            get {
                return this.iDNumberField;
            }
            set {
                this.iDNumberField = value;
            }
        }
        
        /// <remarks/>
        public string HazardousMaterialsDescription {
            get {
                return this.hazardousMaterialsDescriptionField;
            }
            set {
                this.hazardousMaterialsDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ClassDivisionNumber {
            get {
                return this.classDivisionNumberField;
            }
            set {
                this.classDivisionNumberField = value;
            }
        }
        
        /// <remarks/>
        public string SubRiskClass {
            get {
                return this.subRiskClassField;
            }
            set {
                this.subRiskClassField = value;
            }
        }
        
        /// <remarks/>
        public string PackagingGroupType {
            get {
                return this.packagingGroupTypeField;
            }
            set {
                this.packagingGroupTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SpecialPermit {
            get {
                return this.specialPermitField;
            }
            set {
                this.specialPermitField = value;
            }
        }
        
        /// <remarks/>
        public string TechnicalNameRequiredIndicator {
            get {
                return this.technicalNameRequiredIndicatorField;
            }
            set {
                this.technicalNameRequiredIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public string AdditionalShippingInformationRequiredIndicator {
            get {
                return this.additionalShippingInformationRequiredIndicatorField;
            }
            set {
                this.additionalShippingInformationRequiredIndicatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0")]
    public partial class ChemicalDataType {
        
        private ChemicalDetailType chemicalDetailField;
        
        private string[] properShippingNameDetailField;
        
        private PackageQuantityLimitDetailType[] packageQuantityLimitDetailField;
        
        /// <remarks/>
        public ChemicalDetailType ChemicalDetail {
            get {
                return this.chemicalDetailField;
            }
            set {
                this.chemicalDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ProperShippingName", IsNullable=false)]
        public string[] ProperShippingNameDetail {
            get {
                return this.properShippingNameDetailField;
            }
            set {
                this.properShippingNameDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PackageQuantityLimitDetail")]
        public PackageQuantityLimitDetailType[] PackageQuantityLimitDetail {
            get {
                return this.packageQuantityLimitDetailField;
            }
            set {
                this.packageQuantityLimitDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0")]
    public partial class ChemicalRecordResultsType {
        
        private string chemicalRecordIdentifierField;
        
        private string aDRPointsField;
        
        /// <remarks/>
        public string ChemicalRecordIdentifier {
            get {
                return this.chemicalRecordIdentifierField;
            }
            set {
                this.chemicalRecordIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string ADRPoints {
            get {
                return this.aDRPointsField;
            }
            set {
                this.aDRPointsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0")]
    public partial class PackageResultsType {
        
        private string packageIdentifierField;
        
        private string accessibleIndicatorField;
        
        private string europeBUIndicatorField;
        
        private ChemicalRecordResultsType[] chemicalRecordResultsField;
        
        /// <remarks/>
        public string PackageIdentifier {
            get {
                return this.packageIdentifierField;
            }
            set {
                this.packageIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string AccessibleIndicator {
            get {
                return this.accessibleIndicatorField;
            }
            set {
                this.accessibleIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public string EuropeBUIndicator {
            get {
                return this.europeBUIndicatorField;
            }
            set {
                this.europeBUIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ChemicalRecordResults")]
        public ChemicalRecordResultsType[] ChemicalRecordResults {
            get {
                return this.chemicalRecordResultsField;
            }
            set {
                this.chemicalRecordResultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class ElementIdentifierType {
        
        private string codeField;
        
        private string valueField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class ElementLevelInformationType {
        
        private string levelField;
        
        private ElementIdentifierType[] elementIdentifierField;
        
        /// <remarks/>
        public string Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ElementIdentifier")]
        public ElementIdentifierType[] ElementIdentifier {
            get {
                return this.elementIdentifierField;
            }
            set {
                this.elementIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class DetailType {
        
        private string codeField;
        
        private string descriptionField;
        
        private ElementLevelInformationType elementLevelInformationField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public ElementLevelInformationType ElementLevelInformation {
            get {
                return this.elementLevelInformationField;
            }
            set {
                this.elementLevelInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class CodeDescriptionType {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class ResponseType {
        
        private CodeDescriptionType responseStatusField;
        
        private CodeDescriptionType[] alertField;
        
        private DetailType[] alertDetailField;
        
        private TransactionReferenceType transactionReferenceField;
        
        /// <remarks/>
        public CodeDescriptionType ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Alert")]
        public CodeDescriptionType[] Alert {
            get {
                return this.alertField;
            }
            set {
                this.alertField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AlertDetail")]
        public DetailType[] AlertDetail {
            get {
                return this.alertDetailField;
            }
            set {
                this.alertDetailField = value;
            }
        }
        
        /// <remarks/>
        public TransactionReferenceType TransactionReference {
            get {
                return this.transactionReferenceField;
            }
            set {
                this.transactionReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class TransactionReferenceType {
        
        private string customerContextField;
        
        private string transactionIdentifierField;
        
        /// <remarks/>
        public string CustomerContext {
            get {
                return this.customerContextField;
            }
            set {
                this.customerContextField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionIdentifier {
            get {
                return this.transactionIdentifierField;
            }
            set {
                this.transactionIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0")]
    public partial class ChemicalRecordType {
        
        private string chemicalRecordIdentifierField;
        
        private string reportableQuantityField;
        
        private string classDivisionNumberField;
        
        private string subRiskClassField;
        
        private string iDNumberField;
        
        private string packagingGroupTypeField;
        
        private string quantityField;
        
        private string uOMField;
        
        private string packagingInstructionCodeField;
        
        private string properShippingNameField;
        
        private string technicalNameField;
        
        private string additionalDescriptionField;
        
        private string packagingTypeField;
        
        private string hazardLabelRequiredField;
        
        private string packagingTypeQuantityField;
        
        private string commodityRegulatedLevelCodeField;
        
        private string transportCategoryField;
        
        private string tunnelRestrictionCodeField;
        
        private string allPackedInOneIndicatorField;
        
        /// <remarks/>
        public string ChemicalRecordIdentifier {
            get {
                return this.chemicalRecordIdentifierField;
            }
            set {
                this.chemicalRecordIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string ReportableQuantity {
            get {
                return this.reportableQuantityField;
            }
            set {
                this.reportableQuantityField = value;
            }
        }
        
        /// <remarks/>
        public string ClassDivisionNumber {
            get {
                return this.classDivisionNumberField;
            }
            set {
                this.classDivisionNumberField = value;
            }
        }
        
        /// <remarks/>
        public string SubRiskClass {
            get {
                return this.subRiskClassField;
            }
            set {
                this.subRiskClassField = value;
            }
        }
        
        /// <remarks/>
        public string IDNumber {
            get {
                return this.iDNumberField;
            }
            set {
                this.iDNumberField = value;
            }
        }
        
        /// <remarks/>
        public string PackagingGroupType {
            get {
                return this.packagingGroupTypeField;
            }
            set {
                this.packagingGroupTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public string UOM {
            get {
                return this.uOMField;
            }
            set {
                this.uOMField = value;
            }
        }
        
        /// <remarks/>
        public string PackagingInstructionCode {
            get {
                return this.packagingInstructionCodeField;
            }
            set {
                this.packagingInstructionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ProperShippingName {
            get {
                return this.properShippingNameField;
            }
            set {
                this.properShippingNameField = value;
            }
        }
        
        /// <remarks/>
        public string TechnicalName {
            get {
                return this.technicalNameField;
            }
            set {
                this.technicalNameField = value;
            }
        }
        
        /// <remarks/>
        public string AdditionalDescription {
            get {
                return this.additionalDescriptionField;
            }
            set {
                this.additionalDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string PackagingType {
            get {
                return this.packagingTypeField;
            }
            set {
                this.packagingTypeField = value;
            }
        }
        
        /// <remarks/>
        public string HazardLabelRequired {
            get {
                return this.hazardLabelRequiredField;
            }
            set {
                this.hazardLabelRequiredField = value;
            }
        }
        
        /// <remarks/>
        public string PackagingTypeQuantity {
            get {
                return this.packagingTypeQuantityField;
            }
            set {
                this.packagingTypeQuantityField = value;
            }
        }
        
        /// <remarks/>
        public string CommodityRegulatedLevelCode {
            get {
                return this.commodityRegulatedLevelCodeField;
            }
            set {
                this.commodityRegulatedLevelCodeField = value;
            }
        }
        
        /// <remarks/>
        public string TransportCategory {
            get {
                return this.transportCategoryField;
            }
            set {
                this.transportCategoryField = value;
            }
        }
        
        /// <remarks/>
        public string TunnelRestrictionCode {
            get {
                return this.tunnelRestrictionCodeField;
            }
            set {
                this.tunnelRestrictionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AllPackedInOneIndicator {
            get {
                return this.allPackedInOneIndicatorField;
            }
            set {
                this.allPackedInOneIndicatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0")]
    public partial class PackageWeightUOMType {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0")]
    public partial class PackageWeightType {
        
        private string weightField;
        
        private PackageWeightUOMType unitOfMeasurementField;
        
        /// <remarks/>
        public string Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public PackageWeightUOMType UnitOfMeasurement {
            get {
                return this.unitOfMeasurementField;
            }
            set {
                this.unitOfMeasurementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0")]
    public partial class PackageType {
        
        private string packageIdentifierField;
        
        private PackageWeightType packageWeightField;
        
        private string qValueField;
        
        private string overPackedIndicatorField;
        
        private string transportationModeField;
        
        private string emergencyPhoneField;
        
        private string emergencyContactField;
        
        private ChemicalRecordType[] chemicalRecordField;
        
        /// <remarks/>
        public string PackageIdentifier {
            get {
                return this.packageIdentifierField;
            }
            set {
                this.packageIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public PackageWeightType PackageWeight {
            get {
                return this.packageWeightField;
            }
            set {
                this.packageWeightField = value;
            }
        }
        
        /// <remarks/>
        public string QValue {
            get {
                return this.qValueField;
            }
            set {
                this.qValueField = value;
            }
        }
        
        /// <remarks/>
        public string OverPackedIndicator {
            get {
                return this.overPackedIndicatorField;
            }
            set {
                this.overPackedIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public string TransportationMode {
            get {
                return this.transportationModeField;
            }
            set {
                this.transportationModeField = value;
            }
        }
        
        /// <remarks/>
        public string EmergencyPhone {
            get {
                return this.emergencyPhoneField;
            }
            set {
                this.emergencyPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string EmergencyContact {
            get {
                return this.emergencyContactField;
            }
            set {
                this.emergencyContactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ChemicalRecord")]
        public ChemicalRecordType[] ChemicalRecord {
            get {
                return this.chemicalRecordField;
            }
            set {
                this.chemicalRecordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0")]
    public partial class ServiceType {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0")]
    public partial class AddressType {
        
        private string addressLineField;
        
        private string cityField;
        
        private string stateProvinceCodeField;
        
        private string postalCodeField;
        
        private string countryCodeField;
        
        /// <remarks/>
        public string AddressLine {
            get {
                return this.addressLineField;
            }
            set {
                this.addressLineField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string StateProvinceCode {
            get {
                return this.stateProvinceCodeField;
            }
            set {
                this.stateProvinceCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0")]
    public partial class ShipmentType {
        
        private string shipperNumberField;
        
        private AddressType shipFromAddressField;
        
        private AddressType shipToAddressField;
        
        private ServiceType serviceField;
        
        private string regulationSetField;
        
        private PackageType[] packageField;
        
        /// <remarks/>
        public string ShipperNumber {
            get {
                return this.shipperNumberField;
            }
            set {
                this.shipperNumberField = value;
            }
        }
        
        /// <remarks/>
        public AddressType ShipFromAddress {
            get {
                return this.shipFromAddressField;
            }
            set {
                this.shipFromAddressField = value;
            }
        }
        
        /// <remarks/>
        public AddressType ShipToAddress {
            get {
                return this.shipToAddressField;
            }
            set {
                this.shipToAddressField = value;
            }
        }
        
        /// <remarks/>
        public ServiceType Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
        
        /// <remarks/>
        public string RegulationSet {
            get {
                return this.regulationSetField;
            }
            set {
                this.regulationSetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Package")]
        public PackageType[] Package {
            get {
                return this.packageField;
            }
            set {
                this.packageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class RequestType {
        
        private string[] requestOptionField;
        
        private string subVersionField;
        
        private TransactionReferenceType transactionReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RequestOption")]
        public string[] RequestOption {
            get {
                return this.requestOptionField;
            }
            set {
                this.requestOptionField = value;
            }
        }
        
        /// <remarks/>
        public string SubVersion {
            get {
                return this.subVersionField;
            }
            set {
                this.subVersionField = value;
            }
        }
        
        /// <remarks/>
        public TransactionReferenceType TransactionReference {
            get {
                return this.transactionReferenceField;
            }
            set {
                this.transactionReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")]
    public partial class UPSSecurityServiceAccessToken {
        
        private string accessLicenseNumberField;
        
        /// <remarks/>
        public string AccessLicenseNumber {
            get {
                return this.accessLicenseNumberField;
            }
            set {
                this.accessLicenseNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0")]
    public partial class AcceptanceAuditPreCheckRequest {
        
        private RequestType requestField;
        
        private string originRecordTransactionTimestampField;
        
        private ShipmentType shipmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
        public RequestType Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        public string OriginRecordTransactionTimestamp {
            get {
                return this.originRecordTransactionTimestampField;
            }
            set {
                this.originRecordTransactionTimestampField = value;
            }
        }
        
        /// <remarks/>
        public ShipmentType Shipment {
            get {
                return this.shipmentField;
            }
            set {
                this.shipmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0")]
    public partial class AcceptanceAuditPreCheckResponse {
        
        private ResponseType responseField;
        
        private string shipperNumberField;
        
        private ServiceType serviceField;
        
        private string regulationSetField;
        
        private PackageResultsType[] packageResultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
        public ResponseType Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        public string ShipperNumber {
            get {
                return this.shipperNumberField;
            }
            set {
                this.shipperNumberField = value;
            }
        }
        
        /// <remarks/>
        public ServiceType Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
        
        /// <remarks/>
        public string RegulationSet {
            get {
                return this.regulationSetField;
            }
            set {
                this.regulationSetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PackageResults")]
        public PackageResultsType[] PackageResults {
            get {
                return this.packageResultsField;
            }
            set {
                this.packageResultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0")]
    public partial class ChemicalReferenceDataRequest {
        
        private RequestType requestField;
        
        private string iDNumberField;
        
        private string properShippingNameField;
        
        private string shipperNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
        public RequestType Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        public string IDNumber {
            get {
                return this.iDNumberField;
            }
            set {
                this.iDNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ProperShippingName {
            get {
                return this.properShippingNameField;
            }
            set {
                this.properShippingNameField = value;
            }
        }
        
        /// <remarks/>
        public string ShipperNumber {
            get {
                return this.shipperNumberField;
            }
            set {
                this.shipperNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/DangerousGoodsUtility/v1.0")]
    public partial class ChemicalReferenceDataResponse {
        
        private ResponseType responseField;
        
        private ChemicalDataType[] chemicalDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
        public ResponseType Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ChemicalData")]
        public ChemicalDataType[] ChemicalData {
            get {
                return this.chemicalDataField;
            }
            set {
                this.chemicalDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ProcessAcceptanceAuditPreCheckCompletedEventHandler(object sender, ProcessAcceptanceAuditPreCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessAcceptanceAuditPreCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessAcceptanceAuditPreCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AcceptanceAuditPreCheckResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AcceptanceAuditPreCheckResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ProcessChemicalReferenceDataCompletedEventHandler(object sender, ProcessChemicalReferenceDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessChemicalReferenceDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessChemicalReferenceDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ChemicalReferenceDataResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ChemicalReferenceDataResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591